# Generated by Django 4.1.3 on 2022-11-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topiccomment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_comments',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='topiccomment.tbl_topics'),
        ),
    ]
